---
services: docker

env:
  - JENKINS_ENVIRONMENT=travis

script:
  - set -e
  # Start a Docker container.
  - 'docker-compose up -d'

  # Install dependencies and run Ansible playbook.
  - 'docker exec --tty drupal-jenkins env TERM=xterm bash -c "cd /etc/ansible/playbook; ansible-galaxy install -r requirements.yml"'

  # Run Ansible playbook (first with a syntax check, then for real).
  - 'docker exec --tty drupal-jenkins bash -c /etc/ansible/playbook/scripts/run-playbook.sh'

  # Run the playbook again to check for idempotence.
  - idempotence=$(mktemp)
  - 'docker exec drupal-jenkins bash -c "cd /etc/ansible/playbook; ansible-playbook -i inventory/${JENKINS_ENVIRONMENT} main.yml --extra-vars \"{jenkins_test_mode: True}\"" | tee -a ${idempotence}'
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - set +e
