---
version: '3'
services:
  jenkins:
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    container_name: drupal-jenkins
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/etc/ansible/playbook:rw,delegated
      - ./jenkins_home:/var/lib/jenkins:rw,delegated
    privileged: true
