---
# Ansible Galaxy roles.
- src: geerlingguy.ansible
  version: 1.2.0
- src: geerlingguy.certbot
  version: 2.0.1
- src: geerlingguy.java
  version: 1.7.4
- src: geerlingguy.jenkins
  version: 3.2.2
- src: geerlingguy.git
  version: 1.3.0
- src: geerlingguy.nginx
  version: 2.5.0
- src: geerlingguy.security
  version: 1.5.0
- src: geerlingguy.firewall
  version: 2.2.1
- src: geerlingguy.pip
  version: 1.1.0
