---
# Ansible Galaxy roles.
- src: geerlingguy.ansible
  version: 1.2.2
- src: geerlingguy.certbot
  version: 3.0.0
- src: geerlingguy.docker
  version: 2.1.0
- src: geerlingguy.java
  version: 1.7.7
- src: geerlingguy.jenkins
  version: 3.3.1
- src: geerlingguy.git
  version: 2.0.2
- src: geerlingguy.nginx
  version: 2.5.1
- src: geerlingguy.security
  version: 1.6.0
- src: geerlingguy.firewall
  version: 2.3.1
- src: geerlingguy.pip
  version: 1.2.0
