---
# Ansible Galaxy roles.
- src: geerlingguy.ansible
  version: 1.2.0
- src: geerlingguy.certbot
  version: 3.0.0
- src: geerlingguy.java
  version: 1.7.6
- src: geerlingguy.jenkins
  version: 3.2.2
- src: geerlingguy.git
  version: 1.4.1
- src: geerlingguy.nginx
  version: 2.5.0
- src: geerlingguy.security
  version: 1.6.0
- src: geerlingguy.firewall
  version: 2.3.0
- src: geerlingguy.pip
  version: 1.2.0
